test environment. update_method = git-pull
update_method = git-pull

lilie.rohberg.ch: Connecting via ssh (1/1)
============================================================================ Configuring model ... =============================================================================
ERROR: Traceback (most recent call last):
  File "/Users/ksuess/RohbergPloneDeployment/rohbergplonedeployment/.batou/unclean/lib/python3.7/site-packages/batou/remote_core.py", line 373, in <module>
  File "/Users/ksuess/RohbergPloneDeployment/rohbergplonedeployment/.batou/unclean/lib/python3.7/site-packages/batou/remote_core.py", line 289, in git_pull_code
TypeError: a bytes-like object is required, not 'str'